export const REGISTER_LOADING = 'REGISTER_LOADING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_ERROR = 'PROFILE_ERROR'

export const AWARD_LOADING = 'AWARD_LOADING'
export const AWARD_SUCCESS = 'AWARD_SUCCESS'
export const AWARD_ERROR = 'AWARD_ERROR'

export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'


export const STUDENT_LOADING = 'STUDENT_LOADING'
export const STUDENT_SUCCESS = 'STUDENT_SUCCESS'
export const STUDENT_ERROR = 'STUDENT_ERROR'