
export const REGISTER_LOADING = 'REGISTER_LOADING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'

export const PARTNER_LOADING = 'PARTNER_LOADING'
export const PARTNER_SUCCESS = 'PARTNER_SUCCESS'
export const PARTNER_ERROR = 'PARTNER_ERROR'

export const GETPARTNERS_LOADING = 'GETPARTNERS_LOADING'
export const GETPARTNERS_SUCCESS = 'GETPARTNERS_SUCCESS'
export const GETPARTNERS_ERROR = 'GETPARTNERS_ERROR'

export const DELETEPARTNER_LOADING = 'DELETEPARTNER_LOADING'
export const DELETEPARTNER_SUCCESS = 'DELETEPARTNER_SUCCESS'
export const DELETEPARTNER_ERROR = 'DELETEPARTNER_ERROR'

export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_ERROR = 'PROFILE_ERROR'

export const AWARD_LOADING = 'AWARD_LOADING'
export const AWARD_SUCCESS = 'AWARD_SUCCESS'
export const AWARD_ERROR = 'AWARD_ERROR'

export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const PARTNERLOGIN_LOADING = 'PARTNERLOGIN_LOADING'
export const PARTNERLOGIN_SUCCESS = 'PARTNERLOGIN_SUCCESS'
export const PARTNERLOGIN_ERROR = 'PARTNERLOGIN_ERROR'

export const STUDENT_LOADING = 'STUDENT_LOADING'
export const STUDENT_SUCCESS = 'STUDENT_SUCCESS'
export const STUDENT_ERROR = 'STUDENT_ERROR'

export const EDIT_LOADING = 'EDIT_LOADING'
export const EDIT_SUCCESS = 'EDIT_SUCCESS'
export const EDIT_ERROR = 'EDIT_ERROR'

export const EDITAWARD_LOADING = 'EDITAWARD_LOADING'
export const EDITAWARD_SUCCESS = 'EDITAWARD_SUCCESS'
export const EDITAWARD_ERROR = 'EDITAWARD_ERROR'

export const EDITSTUDENTBIO_LOADING = 'EDITSTUDENTBIO_LOADING'
export const EDITSTUDENTBIO_SUCCESS = 'EDITSTUDENTBIO_SUCCESS'
export const EDITSTUDENTBIO_ERROR = 'EDITSTUDENTBIO_ERROR'

export const LESSON_LOADING = 'LESSON_LOADING'
export const LESSON_SUCCESS = 'LESSON_SUCCESS'
export const LESSON_ERROR = 'LESSON_ERROR'

export const GETPROFILE_LOADING = 'GETPROFILE_LOADING'
export const GETPROFILE_SUCCESS = 'GETPROFILE_SUCCESS'
export const GETPROFILE_ERROR = 'GETPROFILE_ERROR'

export const GETLECTURESBYAUSER_LOADING = 'GETLECTURESBYAUSER_LOADING'
export const GETLECTURESBYAUSER_SUCCESS = 'GETLECTURESBYAUSER_SUCCESS'
export const GETLECTURESBYAUSER_ERROR = 'GETLECTURESBYAUSER_ERROR'

export const TIMETABLE_LOADING = 'TIMETABLE_LOADING'
export const TIMETABLE_SUCCESS = 'TIMETABLE_SUCCESS'
export const TIMETABLE_ERROR = 'TIMETABLE_ERROR'

export const GETTIMETABLE_LOADING = 'GETTIMETABLE_LOADING'
export const GETTIMETABLE_SUCCESS = 'GETTIMETABLE_SUCCESS'
export const GETTIMETABLE_ERROR = 'GETTIMETABLE_ERROR'

export const DELETEASUBJECT_LOADING = 'DELETEASUBJECT_LOADING'
export const DELETEASUBJECT_SUCCESS = 'DELETEASUBJECT_SUCCESS'
export const DELETEASUBJECT_ERROR = 'DELETEASUBJECT_ERROR'

export const EDITASUBJECT_LOADING = 'EDITASUBJECT_LOADING'
export const EDITASUBJECT_SUCCESS = 'EDITASUBJECT_SUCCESS'
export const EDITASUBJECT_ERROR = 'EDITASUBJECT_ERROR'


export const DELETEATOPIC_LOADING = 'DELETEATOPIC_LOADING'
export const DELETEATOPIC_SUCCESS = 'DELETEATOPIC_SUCCESS'
export const DELETEATOPIC_ERROR = 'DELETEATOPIC_ERROR'


export const EDITATOPIC_LOADING = 'EDITATOPIC_LOADING'
export const EDITATOPIC_SUCCESS = 'EDITATOPIC_SUCCESS'
export const EDITATOPIC_ERROR = 'EDITATOPIC_ERROR'


export const GETLECTURES_LOADING = 'GETLECTURES_LOADING'
export const GETLECTURES_SUCCESS = 'GETLECTURES_SUCCESS'
export const GETLECTURES_ERROR = 'GETLECTURES_ERROR'


export const GETONELECTURE_LOADING = 'GETONELECTURE_LOADING'
export const GETONELECTURE_SUCCESS = 'GETONELECTURE_SUCCESS'
export const GETONELECTURE_ERROR = 'GETONELECTURE_ERROR'


export const ENROLLECTURE_LOADING = 'ENROLLECTURE_LOADING'
export const ENROLLECTURE_SUCCESS = 'ENROLLECTURE_SUCCESS'
export const ENROLLECTURE_ERROR = 'ENROLLECTURE_ERROR'


export const MYENROLLECTURE_LOADING = 'MYENROLLECTURE_LOADING'
export const MYENROLLECTURE_SUCCESS = 'MYENROLLECTURE_SUCCESS'
export const MYENROLLECTURE_ERROR = 'MYENROLLECTURE_ERROR'


export const CONVERSATION_LOADING = 'CONVERSATION_LOADING'
export const CONVERSATION_SUCCESS = 'CONVERSATION_SUCCESS'
export const CONVERSATION_ERROR = 'CONVERSATION_ERROR'


export const GETUSERCONVERSATION_LOADING = 'GETUSERCONVERSATION_LOADING'
export const GETUSERCONVERSATION_SUCCESS = 'GETUSERCONVERSATION_SUCCESS'
export const GETUSERCONVERSATION_ERROR = 'GETUSERCONVERSATION_ERROR'


export const MESSAGE_LOADING = 'MESSAGE_LOADING'
export const MESSAGE_SUCCESS = 'MESSAGE_SUCCESS'
export const MESSAGE_ERROR = 'MESSAGE_ERROR'

    
export const FETCHMESSAGE_LOADING = 'FETCHMESSAGE_LOADING'
export const FETCHMESSAGE_SUCCESS = 'FETCHMESSAGE_SUCCESS'
export const FETCHMESSAGE_ERROR = 'FETCHMESSAGE_ERROR'