export const lecturerCountry = () => [
  { id: "0", title: "Please choose your country" },
  { id: "1", title: "Nigeria" },
  { id: "2", title: "USA" },
  { id: "3", title: "CANADA" },
  { id: "4", title: "UK" },
];

export const lecturerState = () => [
  { id: "0", title: "Please choose your state" },
  { id: "1", title: "Abuja" },
  { id: "2", title: "Abia" },
  { id: "3", title: "Adamawa" },
  { id: "4", title: "Akwa Ibom" },
  { id: "5", title: "Anambra" },
  { id: "6", title: "Bauchi" },
  { id: "7", title: "Bayelsa" },
  { id: "8", title: "Benue" },
  { id: "9", title: "Borno" },
  { id: "10", title: "Cross River" },
  { id: "11", title: "Delta" },
  { id: "12", title: "Ebonyi" },
  { id: "13", title: "Edo" },
  { id: "14", title: "Ekiti" },
  { id: "15", title: "Enugu" },
  { id: "16", title: "Gombe" },
  { id: "17", title: "Imo" },
  { id: "18", title: "Jigawa" },
  { id: "19", title: "Kaduna" },
  { id: "20", title: "Kano" },
  { id: "21", title: "Katsina" },
  { id: "22", title: "Kebbi" },
  { id: "23", title: "Kogi" },
  { id: "24", title: "Kwara" },
  { id: "25", title: "Lagos" },
  { id: "26", title: "Nassarawa" },
  { id: "27", title: "Niger" },
  { id: "28", title: "Ogun" },
  { id: "29", title: "Ondo" },
  { id: "30", title: "Osun" },
  { id: "31", title: "Oyo" },
  { id: "32", title: "Plateau" },
  { id: "33", title: "Rivers" },
  { id: "34", title: "Sokoto" },
  { id: "35", title: "Taraba" },
  { id: "36", title: "Yobe" },
  { id: "37", title: "Zamfara" },
];

export const lecturerSpecialty = () => [
  { id: "0", title: "Please choose Specialization" },
  { id: "1", title: "Arts" },
  { id: "2", title: "Science" },
  { id: "3", title: "Business" },
  { id: "4", title: "Design" },
  { id: "5", title: "Development" },
  { id: "6", title: "Holidays" },
  { id: "7", title: "Jamb" },
  { id: "8", title: "Marketing" },
  { id: "9", title: "Science" },
  { id: "10", title: "Software" },
  { id: "11", title: "SSCE" },
  { id: "12", title: "University" },
  { id: "13", title: "WAEC" },
];

export const lecturerSubject = () => [
  { id: "0", title: "Please choose Subject" },

  { id: "1", title: "Chemistry" },
  { id: "2", title: "Physics" },
  { id: "3", title: "Maths" },
  { id: "4", title: "Campus courses" },
  { id: "5", title: "English" },
  { id: "6", title: "Literature" },
  { id: "7", title: "Javascript" },
  { id: "8", title: "React" },
  { id: "9", title: "PHP" },
  { id: "10", title: "Python" },
  { id: "11", title: "HTML" },
  { id: "12", title: "CSS" },
  { id: "13", title: "Revit Architecture" },
  { id: "14", title: "Geography" },
  { id: "15", title: "AutoCAD" },
  { id: "16", title: "Photoshop" },
  { id: "17", title: "Video Editing" },
  { id: "18", title: "Music" },
  { id: "19", title: "Excel" },
  { id: "20", title: "AWS" },
  { id: "21", title: "Further Maths" }, 
  { id: "22", title: "Calculus" },
  { id: "23", title: "Economics" },
  { id: "24", title: "Biology" },

];

export const lecturerBank = () => [
  { id: "0", title: "Please choose Bank" },
  { id: "1", title: "Access" },
  { id: "2", title: "First" },
  { id: "3", title: "Sterling" },
  { id: "4", title: "Union" },
  { id: "5", title: "U.B.A" },
  { id: "6", title: "FCMB" },
  { id: "7", title: "Fidelity" },
  { id: "8", title: "Stanbic IBTC" },
  { id: "9", title: "WEMA" },
  { id: "10", title: "GTBank" },
  { id: "11", title: "Zennit" }, 
  { id: "12", title: "Heritage" }, 
];

export const signupAs = () => [
  { id: "1", title: "Please who are you"},
  { id: "2", title: "Student" },
  { id: "3", title: "Teacher" },
];
